site_name: NetMon Documentation
nav:
  - Home: index.md
  - About: about.md
  - Features:
    - Features/index.md
    - Devices & Cabling: Features/Devices & Cabling.md
    - IP Address Management: Features/IPAM.md
    - Feature3: Features/Feature3.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Dark mode
      primary: teal
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Light mode
      primary: blue
      accent: deep orange
  custom_dir: docs/overrides
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navgation.sections
    - navigation.tracking
copyright: Copyright &copy; 2025 GB Tech Global
plugins:
   - search
   - awesome-pages
   - section-index
   - print-site:
      path_to_pdf: "assets/NetMon_UserGuide.pdf"